### Obtener todas las categorías
GET http://localhost:3000/categorias

### Obtener una categoría por ID
GET http://localhost:3000/categorias/1

### Crear nueva categoría
POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nombre": "Hogar"
}

### Editar categoría existente
PUT http://localhost:3000/categorias/1
Content-Type: application/json

{
  "nombre": "Electrónica "
}